openapi: 3.0.3
info:
  title: Shopify
  description: 'Shopify API - Laravel implementation'
  contact:
    name: 'Evgeny Kalashnkov'
    url: 'https://shopify.test'
    email: ekalashnikov@gmail.com
  license:
    name: MIT
    url: 'https://github.com/infinite-system/shopify'
  version: 1.0.0
servers:
  -
    url: 'http://shopify.test/api'
    description: 'Default Environment'
security:
  -
    BearerAuth: []
paths:
  /api/products:
    get:
      parameters: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ProductResource'
                  links:
                    $ref: '#/components/schemas/ResourceLinks'
                  meta:
                    $ref: '#/components/schemas/ResourceMeta'
        401:
          description: Unauthenticated
        403:
          description: Unauthorized
      summary: 'Get a list of products'
      tags:
        - 'Product Api'
    post:
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        201:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/ProductResource'
        401:
          description: Unauthenticated
        403:
          description: Unauthorized
        422:
          description: 'Validation error'
      summary: 'Create product'
      tags:
        - 'Product Api'
  /api/products/search:
    post:
      parameters: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ProductResource'
                  links:
                    $ref: '#/components/schemas/ResourceLinks'
                  meta:
                    $ref: '#/components/schemas/ResourceMeta'
        401:
          description: Unauthenticated
        403:
          description: Unauthorized
      summary: 'Search for products'
      tags:
        - 'Product Api'
  '/api/products/{product}':
    get:
      parameters:
        -
          schema:
            type: integer
          name: product
          in: path
          required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/ProductResource'
        401:
          description: Unauthenticated
        403:
          description: Unauthorized
        404:
          description: 'Resource not found'
      summary: 'Get product'
      tags:
        - 'Product Api'
    patch:
      parameters:
        -
          schema:
            type: integer
          name: product
          in: path
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/ProductResource'
        401:
          description: Unauthenticated
        403:
          description: Unauthorized
        404:
          description: 'Resource not found'
        422:
          description: 'Validation error'
      summary: 'Update product'
      tags:
        - 'Product Api'
    delete:
      parameters:
        -
          schema:
            type: integer
          name: product
          in: path
          required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/ProductResource'
        401:
          description: Unauthenticated
        403:
          description: Unauthorized
        404:
          description: 'Resource not found'
      summary: 'Delete product'
      tags:
        - 'Product Api'
  '/api/products/{product}/restore':
    post:
      parameters:
        -
          schema:
            type: integer
          name: product
          in: path
          required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/ProductResource'
        401:
          description: Unauthenticated
        403:
          description: Unauthorized
        404:
          description: 'Resource not found'
      summary: 'Restore product'
      tags:
        - 'Product Api'
  /api/products/batch:
    post:
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                resources:
                  type: array
                  items:
                    $ref: '#/components/schemas/Product'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ProductResource'
        422:
          description: 'Validation error'
        401:
          description: Unauthenticated
        403:
          description: Unauthorized
        404:
          description: 'Resource not found'
      summary: 'Create a batch of products'
      tags:
        - 'Product Api'
    patch:
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                resources:
                  type: object
                  properties:
                    '{key}':
                      $ref: '#/components/schemas/Product'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ProductResource'
        422:
          description: 'Validation error'
        401:
          description: Unauthenticated
        403:
          description: Unauthorized
        404:
          description: 'Resource not found'
      summary: 'Update a batch of products'
      tags:
        - 'Product Api'
    delete:
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                resources:
                  type: array
                  items:
                    type: integer
                    description: 'A list of resource IDs'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ProductResource'
        422:
          description: 'Validation error'
        401:
          description: Unauthenticated
        403:
          description: Unauthorized
        404:
          description: 'Resource not found'
      summary: 'Delete a batch of products'
      tags:
        - 'Product Api'
  /api/products/batch/restore:
    post:
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                resources:
                  type: array
                  items:
                    type: integer
                    description: 'A list of resource IDs'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ProductResource'
        422:
          description: 'Validation error'
        401:
          description: Unauthenticated
        403:
          description: Unauthorized
        404:
          description: 'Resource not found'
      summary: 'Restore a batch of products'
      tags:
        - 'Product Api'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    Product:
      title: Product
      type: object
      properties:
        name:
          type: string
        description:
          type: string
          nullable: true
        price:
          type: number
        image:
          type: string
          nullable: true
        quantity:
          type: integer
        details:
          type: string
          nullable: true
    ProductResource:
      title: ProductResource
      allOf:
        -
          $ref: '#/components/schemas/Product'
        -
          type: object
          properties:
            id:
              type: integer
            created_at:
              type: string
              nullable: true
              format: date-time
            updated_at:
              type: string
              nullable: true
              format: date-time
    ResourceLinks:
      title: ResourceLinks
      type: object
      properties:
        first:
          type: string
          format: uri
        last:
          type: string
          format: uri
        prev:
          type: string
          format: uri
        next:
          type: string
          format: uri
    ResourceMeta:
      title: ResourceMeta
      type: object
      properties:
        current_page:
          type: integer
        from:
          type: integer
        last_page:
          type: integer
        path:
          type: string
        per_page:
          type: integer
        to:
          type: integer
        total:
          type: integer
tags:
  -
    name: 'Product Api'
    description: 'API documentation for Product Api'
  -
    name: 'Product Api'
    description: 'API documentation for Product Api'
